services:

  postgres_db:
    container_name: memory_code_postgres
    image: postgres:18
    restart: always
    env_file:
      - ./apps/backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend

  redis_db:
    container_name: memory_code_redis
    image: redis:8.6.0
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend: